//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Key]
        [MinLength(5, ErrorMessage = "ID is too short!"), Required(ErrorMessage = "ID cannot be empty")]
        public string pID { get; set; }
        [MinLength(5, ErrorMessage = "Name is too short!"), Required(ErrorMessage = "Name cannot be empty")]
        public string pName { get; set; }
        [Range(1, 9999, ErrorMessage = "Least 1 piece"), Required(ErrorMessage = "Price cannot be empty")]
        public Nullable<int> pSoLuong { get; set; }
        [Range(0, 99999999, ErrorMessage = "input right price!"), Required(ErrorMessage = "Piece cannot be empty")]
        public Nullable<int> pGia { get; set; }
        public string pImg { get; set; }
    }
}
