//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [Key]
        [MinLength(5, ErrorMessage = "Name is too short"), Required(ErrorMessage = "Name cannot be empty!")]
        public string Username { get; set; }
        [MinLength(6, ErrorMessage = "Password too short"), Required(ErrorMessage = "Password cannot be empty")]

        public string Password { get; set; }
        public string nickname { get; set; }
        public string email { get; set; }
        public string imgAva { get; set; }
        public string Role { get; set; }
    }
}
